name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-drafter:
    name: Release Drafter
    environment: release-drafter
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@6db134d15f3909ccc9eefd369f02bd1e9cffdf97 # v6.2.0
        id: drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7

      - name: Update version files
        run: |
          sed -i "s/\"version\": .*/\"version\": \"${{ steps.drafter.outputs.resolved_version }}\",/g" library.json
          sed -i "s/^version = .*/version = \"${{ steps.drafter.outputs.resolved_version }}\"/" pyproject.toml

      - name: Regenerate lockfile
        run: uv lock

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "Bump version to ${{ steps.drafter.outputs.resolved_version }} [skip ci]"
            git push
          fi
